### ISSUE TITLE
Capability to simultaneously support over 10 players.

### ISSUE THREAD

**Issue by SamuelPozzobon** [meyfa/CobolCraft#215]
I am currently working on enhancing the software’s capabilities to accommodate over 10 concurrent players on the server.

Upon reviewing the source code, I believe there are potential avenues for implementing this enhancement. 

I have added a new line to the server.properties file, named “max-players.” I have modified the MAX-PLAYERS field to be a PIC 9(4) EXTERNAL, which allows me to manipulate the effective number of players by reading the properties. On the OCCURS side, I am limited to a certain number of elements. Therefore, theoretically, I can support a maximum of 1000 players simultaneously.

` 01 MAX-PLAYERS PIC 9(4) EXTERNAL.
      *> Player data. Once a new player is connected, their data is stored here. 
      *> When they disconnect, the client is
      *> set to 0, but the player data remains to be reclaimed if the same player connects again.
           01 PLAYERS EXTERNAL.
            02 PLAYER OCCURS 1000 TIMES. `

I implemented the same functionality to MAX-CLIENTS.

In server-properties.cob, I made the following modifications:

Upon the evaluation of the reading section,
`                           WHEN "max-players"
                               MOVE FUNCTION NUMVAL(ENTRY-VALUE)
                                          TO MAX-PLAYERS
                                                MAX-CLIENTS
                               IF MAX-PLAYERS IS NOT NUMERIC OR 
                                  MAX-PLAYERS < 1
                                    MOVE 1 TO LK-FAILURE
                                    GOBACK
                               END-IF`

On writing: 
`           MOVE "max-players" TO ENTRY-KEY
           MOVE MAX-PLAYERS   TO ENTRY-VALUE
           PERFORM AppendKeyValue `

Upon modifying the maximum number of players, the functionality appears to be operational. However, the displayed and subsequently stored numbers appear to be incomprehensible.

When the max-players number is on "0001":
<img width="884" alt="Screenshot 2024-12-27 at 22 34 24" src="https://github.com/user-attachments/assets/6a8e8096-45a7-4fa5-964c-c34a789d06ba" />

Reverting the MAX-CLIENTS results to a “Cannot accept new connection: no free slots” exception.
Could you please provide a more detailed explanation of the player system?

Thanks for your time.

**Comment by meyfa** [comment]
There can be more connected clients than players due to the handshaking and status request, which require a client but not a player. Only once a client performs the login will it be associated with a player. It follows that there must always be at least as many client slots as player slots.

Like you correctly figured out, the program has to allocate enough memory for the theoretical maximum number of clients and players. Since a packet can be roughly 2 MiB in size and is buffered, this means that a client limit of 1000 would consume >2 GiB of RAM, no matter how many clients are actually connected or what limit is set in `server.properties` (once support for that is added). I don't want to raise CobolCraft's RAM requirements that much.

We might move to dynamically allocated memory to make it possible. However, there are other considerations. The server is quite busy encoding chunk packets and sending them out. Unless we get that optimized, even 10 players might be pushing it.

I'm guessing the incorrect display is due to the fact that CobolCraft uses almost exclusively `BINARY-` data types which are not compatible with `PIC 9(4)`.

By the way, if `MAX-PLAYERS` is configurable, it should become part of DD-SERVER-PROPERTIES.cpy.

**Comment by SamuelPozzobon** [comment]
I appreciate your response.

Today, I successfully pushed the maximum client limit of 100 and the system appears to be functioning optimally.

However, I am unable to conduct further testing with a larger number of concurrent players due to the absence of a suitable testing environment with other players.

You can view the modifications on my fork. If possible, I can initiate a pull request.
https://github.com/SamuelPozzobon/CobolCraft

**Comment by SamuelPozzobon** [comment]
Update on the testing progress:

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/c098eda6-ecf3-4cf8-8aa3-8d32837f21b6" />

If the player’s maximum slot is set to 1, it is limited to only one active player. Therefore, the appropriate exception to be thrown is “Cannot accept new connection: no free slots.” 
<img width="535" alt="Screenshot 2024-12-28 at 14 19 48" src="https://github.com/user-attachments/assets/a89e40e6-8ab8-4d52-8571-576a11bb7e59" />

**Comment by SamuelPozzobon** [comment]
Closing this issue due to pull request
https://github.com/meyfa/CobolCraft/pull/222
